---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    broken_arrays:
      single_server_list:
        - server1
      multiple_server_list:
        - server2
        - server3
        - server4

platforms:
#  - name: centos-5.11
#  - name: centos-6.8
#  - name: centos-7.2
#  - name: ubuntu-12.04
#  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: works
    driver:
      require_chef_omnibus: 12.15.19
    run_list:
      - recipe[broken_arrays]
  - name: broken
    driver:
      require_chef_omnibus: 12.16.42
    run_list:
      - recipe[broken_arrays]
